
name: "install"

on:
  push:

jobs:
  install_test_by_curl:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "install by curl"
        run: curl https://raw.githubusercontent.com/tac0x2a/dotfiles/master/install.sh | bash

  install_test_by_clone:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "install by clone"
        run:
          git clone git@github.com:tac0x2a/dotfiles.git ~/.dotfiles
          cd .dotfiles
          chmod +x ./install.sh
          ./install.sh
